### ISSUE TITLE
Could not initialize class com.drew.imaging.jpeg.JpegMetadataReader

### ISSUE THREAD

**Issue by AndKe** [activityworkshop/GpsPrune#15]
Unable to load .jpg photo positions.
- it may be caused by recent upgrade to Ubuntu 17.10 (from 17.04)

Link: com/adobe/xmp/XMPException
java.lang.NoClassDefFoundError: com/adobe/xmp/XMPException
	at com.drew.imaging.jpeg.JpegMetadataReader.<clinit>(JpegMetadataReader.java:57)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:111)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:161)
	at tim.prune.jpeg.ExternalExifLibrary.getJpegData(ExternalExifLibrary.java:36)
	at tim.prune.jpeg.ExifGateway.getJpegData(ExifGateway.java:46)
	at tim.prune.load.JpegLoader.createPhoto(JpegLoader.java:227)
	at tim.prune.load.JpegLoader.processFile(JpegLoader.java:204)
	at tim.prune.load.JpegLoader.processFileList(JpegLoader.java:172)
	at tim.prune.load.JpegLoader.run(JpegLoader.java:127)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.adobe.xmp.XMPException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
Link: Could not initialize class com.drew.imaging.jpeg.JpegMetadataReader
java.lang.NoClassDefFoundError: Could not initialize class com.drew.imaging.jpeg.JpegMetadataReader
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:111)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:161)
	at tim.prune.jpeg.ExternalExifLibrary.getJpegData(ExternalExifLibrary.java:36)
	at tim.prune.jpeg.ExifGateway.getJpegData(ExifGateway.java:46)
	at tim.prune.load.JpegLoader.createPhoto(JpegLoader.java:227)
	at tim.prune.load.JpegLoader.processFile(JpegLoader.java:204)
	at tim.prune.load.JpegLoader.processFileList(JpegLoader.java:172)
	at tim.prune.load.JpegLoader.run(JpegLoader.java:127)
	at java.lang.Thread.run(Thread.java:748)

**Comment by activityworkshop** [comment]
Hi, it sounds like it can't find the libmetadata classes (NoClassDefFoundError).  Please check which versions of gpsprune and libmetadata-extractor-java - the latter should be 2.10.1.  Make sure both are from Ubuntu 17.10, as the libmetadata-extractor-java package had some changes in this release.  The references to com.adobe.xmp refer to the libxmpcore-java package, which should have been automatically included too, and shouldn't have changed.

Also, are you using /usr/bin/gpsprune to launch GpsPrune, or some other way?  Maybe there's a problem with it finding the right jars?  I don't have a current version of Ubuntu to test this on right now, but in general it should work with libmetadata-extractor-java 2.10.1.

**Comment by AndKe** [comment]
Hi thanks for looking into this.
I were launching it using the GUI shortcut, , but  /usr/bin/gpsprune gives same result.
libmetadata-extractor-java is ver 2.10.1-2 (a part of the Ubuntu, I have no other PPA's)
libxmpcore-java 5.1.2-3 is ther too.

The issue is reproduced on three Ubuntu 17.04 > 17.10 upgraded systems, on all three, GPSPrune worked fine before upgrade.

**Comment by activityworkshop** [comment]
Here is what I've tried so far:
* From packages.ubuntu.com, I manually downloaded gpsprune_18.6-2_all.deb, libmetadata-extractor-java_2.10.1-2_all.deb and libxmpcore-java_5.1.2-3_all.deb.
* Using "dpkg-deb", I took out _just_ the jar files from these packages to give me gpsprune.jar, metadata-extractor.jar and xmpcore-5.1.2.jar.
* Using "java -cp metadata-extractor.jar:xmpcore-5.1.2.jar:gpsprune.jar tim.prune.GpsPrune" I ran GpsPrune, loaded various jpegs and the coordinates were successfully extracted and displayed.

So although that test isn't the same as what you've got, it indicates to me that the jar files in your packages are ok at least.  Maybe there's something wrong with your paths or shortcuts to these jars that prevent it from finding them properly?

Do you have a live version of Ubuntu 17.10 to try out?  That would at least tell us whether it is a problem for every 17.10 system or just something to do with the way you upgraded from 17.04.

**Comment by AndKe** [comment]
Hi, I do not have a live one, - and are unable to get one now.
if its upgraded-only then it happened to all three of my Ubuntu computers

**Comment by AndKe** [comment]
clean installed a virtual Ubuntu 17.10 , installed gpsprune from software center, same issue.
you can say this affects everybody that have installed or upgraded to 17.10

**Comment by activityworkshop** [comment]
Thanks for experimenting with this.  I will try it out myself when I get chance.

It might be interesting for you to see if you have the following files:
```
/usr/share/gpsprune/gpsprune.jar
/usr/share/java/metadata-extractor-2.10.1.jar
/usr/share/java/metadata-extractor.jar
/usr/share/java/xmpcore-5.1.2.jar
/usr/share/java/xmpcore.jar
```

and use "ls -l" to see if the file sizes look ok.
You should then have the same files as I had, and the command "java -cp /usr/share/java/metadata-extractor.jar:/usr/share/java/xmpcore-5.1.2.jar:/usr/share/gpsprune/gpsprune.jar tim.prune.GpsPrune" should (I hope!) give the same results as I had, namely loading coordinates out of jpegs with no errors.

Another option for you is to use the version 18.6 of GpsPrune downloaded from gpsprune.activityworkshop.net, and this should also read coordinates from jpegs properly for you.  The disadvantage is that you would miss the nice integration that the ubuntu package gives you.

**Comment by AndKe** [comment]
-rw-r--r-- 1 root root 1378759 juli  21 19:55 /usr/share/gpsprune/gpsprune.jar
lrwxrwxrwx 1 root root 22 juli  21 12:37
/usr/share/java/metadata-extractor-2.10.1.jar ->
metadata-extractor.jar
-rw-r--r-- 1 root root 492145 juli  21 12:37
/usr/share/java/metadata-extractor.jar
-rw-r--r-- 1 root root 122265 mai   21  2015 /usr/share/java/xmpcore-5.1.2.jar
lrwxrwxrwx 1 root root 17 mai   21  2015 /usr/share/java/xmpcore.jar
-> xmpcore-5.1.2.jar


I have 18.6 build 343 from Ubuntu.,   ,the java command you posted, works
fine.

The simplest fix for me would be to make the .desktop file that executes: "java
-cp /usr/share/java/metadata-extractor.jar:/usr/share/java/
xmpcore-5.1.2.jar:/usr/share/gpsprune/gpsprune.jar tim.prune.GpsPrune"

whats the cause of this issue anyway ?

**Comment by activityworkshop** [comment]
I managed to confirm that it's also a problem with a live copy of Ubuntu 17.10, so it's nothing to do with the upgrade from 17.04.  The jars look basically ok but GpsPrune can't find the xmpcore classes, apparently because the classpath doesn't include that jar.

I had a look at the jars, and the manifest of GpsPrune's jar correctly references the metadata-extractor.jar.  However, the manifest of the metadata-extractor.jar refers to a file called "xmpcore-debian.jar" instead of "xmpcore.jar" as I would expect.

Therefore I think this is a problem with the packaging of metadata-extractor, but I don't know if it's an Ubuntu problem or a Debian problem.  Maybe @sebastic would be kind enough to have a look whether it's an issue for Buster or not?  It seems that even in Debian Buster there is no file called /usr/share/java/xmpcore-debian.jar.

**Comment by sebastic** [comment]
This issue is also present in Debian unstable (and testing most likely too since it has the same version of the dependencies).

I've submitted a patch for the libmetadata-extractor-java package to fix the Class-Path: [Debian Bug #880746](https://bugs.debian.org/880746)

Once the package is fixed in Debian, that change needs find its way into Ubuntu via a [Stable Release Update](https://wiki.ubuntu.com/StableReleaseUpdates). Someone actually using Ubuntu should do that.

**Comment by sebastic** [comment]
libmetadata-extractor-java (2.10.1-3) has been uploaded to Debian unstable to fix this issue.

My patch was applied in a slightly modified form, so Ubuntu will need to cherry-pick two changes:

 * https://anonscm.debian.org/cgit/pkg-java/libmetadata-extractor-java.git/commit/?id=817c7605b14cd176cd8d7337195c5f995bc02151
 * https://anonscm.debian.org/cgit/pkg-java/libmetadata-extractor-java.git/commit/?id=054b392b486cf7dc81ead3296684424d8a7ba7b3

**Comment by activityworkshop** [comment]
That's brilliant, sebastic, thank you so much!
I've no idea how to trigger an ubuntu merge, but maybe somebody else can help with that.
In any case, it sounds like you have fixed it for Buster, which is awesome.  Although as we discussed, the problem should go away with GpsPrune v19 anyway ;)

**Comment by sebastic** [comment]
The procedure to get this issue fixed in Ubuntu is documented in the Stable Release Update wiki I linked in my earlier post.

**Comment by activityworkshop** [comment]
I think this issue can be closed with the release of GpsPrune version 19, as it no longer depends on libmetadata-extractor-java.

**Comment by sebastic** [comment]
Yes, this issue can be closed.

Ubuntu will sync the gpsprune package from Debian unstable.

**Comment by activityworkshop** [comment]
Package is in Ubuntu Cosmic now so I'll close this.
